# Generated by Django 6.0 on 2026-01-05 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='color',
            field=models.CharField(default='#3b82f6', max_length=7),
        ),
        migrations.AddField(
            model_name='account',
            name='is_debt',
            field=models.BooleanField(default=False),
        ),
    ]
