# Generated by Django 6.0 on 2026-01-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_account_color_account_is_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('account', 'Account'), ('investment', 'Investment'), ('card', 'Card')], default='account', max_length=10),
        ),
    ]
